// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2974.ShifterBot.commands;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2974.ShifterBot.OI;
import org.usfirst.frc2974.ShifterBot.Robot;

/**
 *
 */
public class Drive extends Command {

	OI oi;
	Joystick rightJoystick;
	Joystick leftJoystick;
	double throttle = 0;
	double rX = 0, rX_Set = 0;
	double rX_Abs = 0;
	double right = 0, left = 0;

	/**
	 * Drives da bot
	 */
	public Drive() {
		// Use requires() here to declare subsystem dependencies
		// eg. requires(chassis);

		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		requires(Robot.driveTrain);
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}
	// Called just before this Command runs the first time

	protected void initialize() {
		rightJoystick = Robot.oi.getRightJoystick();
		leftJoystick = Robot.oi.getLeftJoystick();
	}
	// Called repeatedly when this Command is scheduled to runz

	/**
	 * CheeziePoof drive sucks
	 */
	protected void execute() {
		throttle = (-leftJoystick.getY() + 1) / 2;
		rX = rightJoystick.getX();
		rX_Abs = Math.abs(rX);

		rX_Set = rX;
		if (rX_Abs < .15) {
			rX_Set = 0;
		}
//        else if (rX_Abs < .2) {
//            rX_Set = .1;
//        } else if (rX_Abs < .3) {
//            rX_Set = .2;
//        } else if (rX_Abs < .4) {
//            rX_Set = .3;
//        } else if (rX_Abs < .5) {
//            rX_Set = .4;
//        } else if (rX_Abs < .6) {
//            rX_Set = .5;
//        } else if (rX_Abs < .7) {
//            rX_Set = .6;
//        } else if (rX_Abs < .8) {
//            rX_Set = .75;
//        } else if (rX_Abs < .9) {
//            rX_Set = .9;
//        }else if(rX_Abs < 1){
//            rX_Set = 1;
//        }
//        if (rX < 0) {
//            rX_Set *= -1;
//        }
		left = throttle * (rightJoystick.getY() - rX_Set);
		right = throttle * (rightJoystick.getY() + rX_Set);
		Robot.driveTrain.drive(left, right);

        /*if(throttle>.75)Robot.driveTrain.shift(true);
         if(throttle<.25)Robot.driveTrain.shift(false);*/

	}
	// Make this return true when this Command no longer needs to run execute()

	protected boolean isFinished() {
		return false;
	}
	// Called once after isFinished returns true

	protected void end() {
	}
	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run

	protected void interrupted() {
	}
}
