// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2974.Simple;
    
import edu.wpi.first.wpilibj.*;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Solenoid shooterLatch;
    public static Solenoid shooterShaft_1;
    public static Solenoid shooterShaft_2;
    public static Talon drivetrainLeft;
    public static Talon drivetrainRight;
    public static Talon drivetrainLeft_2;
    public static Talon drivetrainRight_2;
    public static Compressor intakeCompressor;
    public static Talon intakeArm;
    public static Talon intakeRoller;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        shooterLatch = new Solenoid(1, 3);
	//LiveWindow.addActuator("Shooter", "Latch", shooterLatch);
        
        shooterShaft_1 = new Solenoid(1, 2);
	//LiveWindow.addActuator("Shooter", "Shaft_1", shooterShaft_1);
        
        shooterShaft_2 = new Solenoid(1, 1);
	//LiveWindow.addActuator("Shooter", "Shaft_2", shooterShaft_2);
        
        drivetrainLeft = new Talon(1, 3);
	//LiveWindow.addActuator("Drivetrain", "Left", (Talon) drivetrainLeft);
        
        drivetrainRight = new Talon(1, 1);
	//LiveWindow.addActuator("Drivetrain", "Right", (Talon) drivetrainRight);
        
        drivetrainLeft_2 = new Talon(1, 4);
	//LiveWindow.addActuator("Drivetrain", "Left_2", (Talon) drivetrainLeft_2);
        
        drivetrainRight_2 = new Talon(1, 2);
	//LiveWindow.addActuator("Drivetrain", "Right_2", (Talon) drivetrainRight_2);
        
        intakeCompressor = new Compressor(1, 14, 1, 1);
	
        
        intakeArm = new Talon(1, 5);
	//LiveWindow.addActuator("Intake", "Arm", (Talon) intakeArm);
        
        intakeRoller = new Talon(1, 6);
	//LiveWindow.addActuator("Intake", "Roller", (Talon) intakeRoller);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
