// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc2974.ShifterBot;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into to a variable name. This provides
 * flexibility changing wiring, makes checking the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public static Talon driveTrainRightTop;
	public static Talon driveTrainRightLow;
	public static Talon driveTrainLeftTop;
	public static Talon driveTrainLeftLow;
	public static Talon driveRight;
	public static Talon driveLeft;
	public static Solenoid shifterShiftSpike;
	public static Compressor compressor;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public static void init() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

		compressor = new Compressor(14, 1);

		driveTrainRightTop = new Talon(1, 1);
		driveTrainRightLow = new Talon(1, 2);
		driveTrainLeftTop = new Talon(1, 3);
		driveTrainLeftLow = new Talon(1, 4);

		shifterShiftSpike = new Solenoid(1, 8);

		LiveWindow.addActuator("Shifter", "ShiftSpike", shifterShiftSpike);

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	}
}
